/**
 * Sets up Claude Code hooks and MCP server config for Claw IM.
 * Patches ~/.claude/settings.json to add PostToolUse, SessionStart hooks and MCP server.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';
import { HOOKS_DIR, CLAWD_PORT, CLAWD_HOST } from '@claw-im/shared';

const CLAUDE_DIR = join(homedir(), '.claude');
const SETTINGS_PATH = join(CLAUDE_DIR, 'settings.json');
const SESSION_START_SH = join(HOOKS_DIR, 'session-start.sh');

interface HookEntry {
  type: string;
  command?: string;
  url?: string;
}

interface HookMatcher {
  matcher: string;
  hooks: HookEntry[];
}

interface McpServer {
  type: string;
  command: string;
  args: string[];
}

interface Settings {
  hooks?: Record<string, HookMatcher[]>;
  mcpServers?: Record<string, McpServer>;
  [key: string]: unknown;
}

function loadSettings(): Settings {
  try {
    const raw = readFileSync(SETTINGS_PATH, 'utf-8');
    return JSON.parse(raw) as Settings;
  } catch {
    return {};
  }
}

function mergeHookArray(
  existing: HookMatcher[] | undefined,
  newEntry: HookMatcher,
): HookMatcher[] {
  const arr = existing ? [...existing] : [];
  const idx = arr.findIndex((m) => m.matcher === newEntry.matcher);

  if (idx === -1) {
    arr.push(newEntry);
  } else {
    const merged = [...arr[idx].hooks];
    for (const hook of newEntry.hooks) {
      const duplicate = merged.some(
        (h) =>
          h.type === hook.type &&
          h.command === hook.command &&
          h.url === hook.url,
      );
      if (!duplicate) {
        merged.push(hook);
      }
    }
    arr[idx] = { ...arr[idx], hooks: merged };
  }

  return arr;
}

function ensureSessionStartScript(): void {
  if (existsSync(SESSION_START_SH)) return;

  mkdirSync(HOOKS_DIR, { recursive: true });

  const script = `#!/usr/bin/env bash
# Claw IM session start hook — auto-generated by clawd init
# This script runs when a Claude Code session starts.
# It pings the daemon to register the session.

CLAWD_URL="http://${CLAWD_HOST}:${CLAWD_PORT}"

curl -s -X POST "$CLAWD_URL/hook/session-start" \\
  -H "Content-Type: application/json" \\
  -d "{\\"session_id\\": \\"$(date +%s)\\", \\"cwd\\": \\"$(pwd)\\"}" \\
  > /dev/null 2>&1 || true
`;

  writeFileSync(SESSION_START_SH, script, { mode: 0o755 });
}

/**
 * Resolves the path to the mcp-entry.js file.
 * Prefers the global npx-installed location, falls back to local dev path.
 */
function getMcpEntryPath(): string {
  // Use npx to resolve — works whether installed globally or locally
  return join(homedir(), 'claw-im', 'packages', 'clawd', 'dist', 'mcp-entry.js');
}

export interface SetupResult {
  settingsPatched: boolean;
  sessionStartCreated: boolean;
  mcpConfigured: boolean;
}

/**
 * Patches ~/.claude/settings.json with Claw IM hooks and MCP server config.
 * Safe to run multiple times — merges without duplicating.
 */
export function setupClaudeCode(): SetupResult {
  const result: SetupResult = {
    settingsPatched: false,
    sessionStartCreated: false,
    mcpConfigured: false,
  };

  // Ensure session-start.sh exists
  const hadScript = existsSync(SESSION_START_SH);
  ensureSessionStartScript();
  result.sessionStartCreated = !hadScript;

  // Load and patch settings
  const settings = loadSettings();

  if (!settings.hooks) {
    settings.hooks = {};
  }

  // PostToolUse hook
  const postToolUseHook: HookMatcher = {
    matcher: '*',
    hooks: [
      {
        type: 'http',
        url: `http://${CLAWD_HOST}:${CLAWD_PORT}/hook/post-tool-use`,
      },
    ],
  };
  settings.hooks.PostToolUse = mergeHookArray(
    settings.hooks.PostToolUse,
    postToolUseHook,
  );

  // SessionStart hook
  const sessionStartHook: HookMatcher = {
    matcher: 'startup',
    hooks: [
      {
        type: 'command',
        command: `bash ${SESSION_START_SH}`,
      },
    ],
  };
  settings.hooks.SessionStart = mergeHookArray(
    settings.hooks.SessionStart,
    sessionStartHook,
  );
  result.settingsPatched = true;

  // MCP server config
  if (!settings.mcpServers) {
    settings.mcpServers = {};
  }
  settings.mcpServers['claw-im'] = {
    type: 'stdio',
    command: 'node',
    args: [getMcpEntryPath()],
  };
  result.mcpConfigured = true;

  // Write settings
  mkdirSync(CLAUDE_DIR, { recursive: true });
  writeFileSync(SETTINGS_PATH, JSON.stringify(settings, null, 2) + '\n', 'utf-8');

  return result;
}
